### ISSUE TITLE
evaluate_vmulti

### ISSUE THREAD

**Issue by fourier20laplace** [wangxr0526/EasIFA#5] opened 2024-09-27 10:04 UTC
<img width="841" alt="github_issue" src="https://github.com/user-attachments/assets/6ab09822-72e7-48a7-a40d-4dbcdecc9bca">
why the code is "all_metrics[key] += metrics"
i think it should be "all_metrics[key] += metrics[key]"

**Comment by fourier20laplace** [comment] 2024-09-27 10:08
Thank you for your amazing work on this project! I  submitted this issue and would really appreciate your feedback when possible.

**Comment by wangxr0526** [comment] 2024-09-27 11:05
Thank you very much for your feedback. This issue indeed occurred during the process of standardizing variable names while organizing the code. We have now fixed this bug and adjusted it to align with the script logic used during our training.

**Closed by wangxr0526** 2024-09-27 11:05 UTC

**Comment by fourier20laplace** [comment] 2024-09-27 11:29
Thanks very much! I would like to know if you made any other changes besides the evaluate_vmulti function, and whether there are similar issues in other places.

**Comment by wangxr0526** [comment] 2024-09-27 17:20
Haha :blush: , thank you for your attention to our work. At the time, due to EasIFA training taking up a significant amount of resources, we were unable to fully debug the training code on a PC after organizing the code. This resulted in not catching the logical errors caused by the standardization of variable names. However, the rest of the code has been debugged and checked multiple times, and no other bugs have been found. If you discover any further issues, please point them out to us. Once again, thank you for your support of our work.  :smile:
